# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb2f24ccd18a36299bb4838d968df892e813db182b984bddcb8139731ea8d47799c38f5d4bafacc2f6505c5213a15ea59c846184bbb0a894cc9f1906ee66c72b

test:
  secret_key_base: 28e539f13dd5fcebc7c6a3c5ba35a5eeb761833bd00245183a51702e6d4599d4449e5cee071b85ba9427970f06de695dbac3b89c9ada6361575f62efa92f6f57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
